{% set name = "propka" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f32bbcafed56e94cc9d3fdb05d9c2faa7485d8a5779aaa79049b9ce0ab052fa

build:
  skip: true  # [py2k]
  number: 0
  entry_points:
    - propka3 = propka.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - propka
    - tests
  commands:
    - propka3 --help
  requires:
    - numpy
    - pandas
    - pytest
    - setuptools

about:
  home: http://propka.org
  license: GNU Lesser General Public v2 (LGPLv2)
  license_family: LGPL
  license_file: LICENSE
  summary: Heuristic pKa calculations with ligands
  dev_url: https://github.com/jensengroup/propka

extra:
  recipe-maintainers:
    - tsenapathi
    - sobolevnrm
