{% set name = "propka" %}
{% set version = "3.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 01b1c68a371ff0449e8e679aca281f71b75eadc2d9d7fb5b227bb929b4d079ec

build:
  number: 1
  entry_points:
    - propka3 = propka.run:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - propka
  commands:
    - propka3 --help
  requires:
    - numpy
    - pandas
    - pytest

about:
  home: http://propka.org
  license: GNU Lesser General Public v2 (LGPLv2)
  license_family: LGPL
  license_file: LICENSE
  summary: Heuristic pKa calculations with ligands
  dev_url: https://github.com/jensengroup/propka

extra:
  recipe-maintainers:
    - tsenapathi
