travis:
  secure:
    BINSTAR_TOKEN: jhqd4PK1be7txYxhAtjAO9LHV5F2zLLb4sjq/gF98Se6h8FzgEbfRd4llW6TMMByWg43Uz8HgzPiC/IpOLu9oNePyaE49Z6EKbrMqXYaICaHnR2Z98SHl0oLcW0ixGotOJ6LC2ztEcXdQTQeIO+l8flPHEUsgEMmrunYHv/Bh4kFqjsdBKnF2On6BwWnQu3FhjDYiQf4EUVTFGFoGZ8MTa0DYafpiWSBFLPI8jjmmoMJtui4h2CJ4R90aIXqY0a4DssTugMzAYpHuhLeTuCQYswQ+hysBfBPK7IQraZCsCiW81peZLgeUOW3g+8840FUdACiZRXkOgJUAG61Du6hG08duY16SLFW2w+ZA6OI/cx3uRPZYUWwYe1mSGtq3yeaQLlaKXKb580QGuZQQ/SUkscOSMUnoz/R9TGsxI9QqGPY1QLOCoUlPKob1LEOPTjyF8DrRC18uadcIdj2jbCH+3odjjlvkrz+AXz0fAdARbR/bNy6vi/RY4iBLbHDdGCW0KDQN5dSBgHglcCYpbBZO+8M2MM2CULlFmJKH2lhrspWL1hpbWRyNmNiAudB6ojnM2IWW+sQ2yvOtqRWI/jgJLMXTD3TRj857cO/q7BqccCUMt79/657DZtF1AhronPww31Qa4Nub5ZSVUhfvat9JtH6gYLXLwCCxuVleSaB6yo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
